name: poke_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^4.0.6
  hive: ^2.2.3
  path_provider: ^2.0.11
  basic_utils: ^3.8.2
  flutter_screenutil: ^5.5.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true



  fonts:

    #-------- NUNITO --------

    - family: NunitoBlack
      fonts: 
        - asset: assets/fonts/Nunito/Nunito-Black.ttf

    - family: NunitoExtraBold
      fonts: 
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
        
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito/Nunito-Light.ttf

